version: "3.8"

services:
  gatsby:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile

    # volumes:
    #   - ./gatsby/src/:/usr/src/gatsby/src
    #   - ./gatsby/gatsby-config.js:/usr/src/gatsby/gatsby-config.js
    #   - ./gatsby/cronjob.js:/usr/src/gatsby/cronjob.js
    # environment:
    #   - GATSBY_WEBPACK_PUBLICPATH=/

    ports:
      - 8081:80
